env:
  RUBY_VERSION: 2.6
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: top_timeline_test

name: Rails tests

# This section configures the trigger for the workflow.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Customize the ruby version depending on your needs
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install Rubocop
        run: gem install rubocop-rails
      - name: Check code
        run: rubocop
  rspec-test:
      name: Rspec
      needs: rubocop-test
      runs-on: ubuntu-latest
      # Docker Hub image that `rspec-test` executes in
      container: node:10.18-jessie
      services:
        postgres:
          image: postgres:latest
          ports:
          - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        # Customize the ruby version depending on your needs
        - name: Setup Ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.6'
        - name: Install dependencies
          run: |
            gem install bundler
            bundle install
        - name: Create database
          run: |
            bundle exec rails db:create RAILS_ENV=test
            bundle exec rails db:migrate RAILS_ENV=test
        - name: Run tests
          run: bundle exec rspec
